const OWNER='irochi1184',REPO='irochi-portfolio',BRANCH='main',API=`https://api.github.com/repos/${OWNER}/${REPO}`,PUBLIC=`https://${OWNER}.github.io/${REPO}/`,DRAFT='irochi_portfolio_draft_v3';
const $=s=>document.querySelector(s), tokenInput=$('#token-input'),remember=$('#remember-session'),loadBtn=$('#load-button'),fileInput=$('#file-input'),publishBtn=$('#publish-button'),statusBadge=$('#connection-status'),editor=$('#editor-panel'),pubPanel=$('#publish-panel'),pubStatus=$('#publish-status'),list=$('#works-list'),empty=$('#empty-state'),tpl=$('#work-template'),historySelect=$('#history-select');
let token=sessionStorage.getItem('irochi_github_token')||'',indexSha='',sourceHtml='',works=[],heroSrc='',dragIndex=-1;
if(token)tokenInput.value=token;
const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function busy(v){document.body.classList.toggle('busy',v)}
function status(html,type=''){pubPanel.classList.remove('hidden');pubStatus.className=`publish-status ${type}`;pubStatus.innerHTML=html}
async function api(path,opt={}){const h={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(opt.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(API+path,{...opt,headers:h});if(!r.ok){let m='';try{m=(await r.json()).message||''}catch{}throw new Error(`${r.status} ${r.statusText}${m?`: ${m}`:''}`)}return r.status===204?null:r.json()}
function dec(b){return new TextDecoder().decode(Uint8Array.from(atob(b.replace(/\n/g,'')),c=>c.charCodeAt(0)))}
function enc(t){const a=new TextEncoder().encode(t);let b='';for(let i=0;i<a.length;i+=32768)b+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(b)}
async function b64(blob){const a=new Uint8Array(await blob.arrayBuffer());let b='';for(let i=0;i<a.length;i+=32768)b+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(b)}
function sizeOf(cls){return cls.includes('large')?'large':cls.includes('tall')?'tall':cls.includes('wide')?'wide':'normal'}
function parseArticle(card,hidden=false){const img=card.querySelector('img'),ds=card.dataset;return{id:ds.workId||crypto.randomUUID(),src:img?.getAttribute('src')||'',title:card.querySelector('h3')?.textContent.trim()||'無題',category:ds.category||'girl',size:sizeOf(card.className),description:ds.description||'',tags:(ds.tags||'').split('|').filter(Boolean),createdAt:ds.createdAt||'',publishedAt:ds.publishedAt||'',focalX:Number(ds.focalX||50),focalY:Number(ds.focalY||35),visible:!hidden,hero:img?.getAttribute('src')===heroSrc,isNew:false,isReplaced:false,originalSrc:'',previewUrl:'',blob:null}}
function parseHtml(html){const d=new DOMParser().parseFromString(html,'text/html');heroSrc=d.querySelector('.main-card img')?.getAttribute('src')||'';const visible=[...d.querySelectorAll('.gallery .work-card')].map(c=>parseArticle(c,false));const hidden=[...(d.querySelector('#portfolio-hidden-works')?.content?.querySelectorAll('.work-card')||[])].map(c=>parseArticle(c,true));works=[...visible,...hidden]}
function snapshot(){return JSON.stringify(works.map(w=>({...w,blob:null,previewUrl:'',isNew:false,isReplaced:false,originalSrc:''})))}
function saveDraft(silent=false){localStorage.setItem(DRAFT,snapshot());if(!silent)status('<p>下書きを保存しました。</p>','success')}
function loadDraft(){const r=localStorage.getItem(DRAFT);if(!r)return status('<p>下書きがありません。</p>','error');works=JSON.parse(r);render();status('<p>下書きを読み込みました。</p>','success')}
function clearDraft(){localStorage.removeItem(DRAFT);status('<p>下書きを破棄しました。</p>','success')}
async function imageToWebp(file){const bm=await createImageBitmap(file),max=2200,sc=Math.min(1,max/Math.max(bm.width,bm.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bm.width*sc));c.height=Math.max(1,Math.round(bm.height*sc));c.getContext('2d').drawImage(bm,0,0,c.width,c.height);bm.close?.();const blob=await new Promise(r=>c.toBlob(r,'image/webp',.88));return blob||new Promise(r=>c.toBlob(r,'image/jpeg',.9))}
function fname(i){const d=new Date(),p=n=>String(n).padStart(2,'0');return`assets/work-${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}-${i}.webp`}
function move(from,to){if(to<0||to>=works.length||from===to)return;const[x]=works.splice(from,1);works.splice(to,0,x);saveDraft(true);render()}
function duplicate(i){const w=works[i],n={...JSON.parse(JSON.stringify(w)),id:crypto.randomUUID(),title:(w.title||'作品')+'（複製）',hero:false,blob:null,previewUrl:'',isNew:false,isReplaced:false,originalSrc:''};works.splice(i+1,0,n);saveDraft(true);render()}
function remove(i){if(!confirm(`「${works[i].title}」を一覧から外しますか？`))return;const wasHero=works[i].hero;works.splice(i,1);if(wasHero&&works[0])works[0].hero=true;saveDraft(true);render()}
function render(){list.innerHTML='';empty.classList.toggle('hidden',works.length>0);works.forEach((w,i)=>{const n=tpl.content.cloneNode(true),card=n.querySelector('.work-editor-card'),img=n.querySelector('.work-preview'),title=n.querySelector('.title-input'),desc=n.querySelector('.description-input'),cat=n.querySelector('.category-select'),size=n.querySelector('.size-select'),tags=n.querySelector('.tags-input'),created=n.querySelector('.created-input'),published=n.querySelector('.published-input'),fx=n.querySelector('.focal-x'),fy=n.querySelector('.focal-y'),fxv=n.querySelector('.fxv'),fyv=n.querySelector('.fyv'),hero=n.querySelector('.hero-radio'),vis=n.querySelector('.visible-checkbox'),rep=n.querySelector('.replace-input'),undo=n.querySelector('.undo-replace');img.src=w.previewUrl||w.src;img.style.objectPosition=`${w.focalX||50}% ${w.focalY||35}%`;title.value=w.title;desc.value=w.description;cat.value=w.category;size.value=w.size;tags.value=(w.tags||[]).join(', ');created.value=w.createdAt||'';published.value=w.publishedAt||'';fx.value=w.focalX??50;fy.value=w.focalY??35;fxv.textContent=fx.value;fyv.textContent=fy.value;hero.checked=!!w.hero;vis.checked=w.visible!==false;n.querySelector('.new-badge').classList.toggle('hidden',!w.isNew);n.querySelector('.replace-badge').classList.toggle('hidden',!w.isReplaced);undo.classList.toggle('hidden',!w.isReplaced);
const change=(el,fn,ev='change')=>el.addEventListener(ev,e=>{fn(e);saveDraft(true)});change(title,e=>w.title=e.target.value,'input');change(desc,e=>w.description=e.target.value,'input');change(cat,e=>w.category=e.target.value);change(size,e=>w.size=e.target.value);change(tags,e=>w.tags=e.target.value.split(',').map(x=>x.trim()).filter(Boolean));change(created,e=>w.createdAt=e.target.value);change(published,e=>w.publishedAt=e.target.value);change(fx,e=>{w.focalX=+e.target.value;fxv.textContent=e.target.value;img.style.objectPosition=`${w.focalX}% ${w.focalY||35}%`},'input');change(fy,e=>{w.focalY=+e.target.value;fyv.textContent=e.target.value;img.style.objectPosition=`${w.focalX||50}% ${w.focalY}%`},'input');hero.addEventListener('change',()=>{works.forEach(x=>x.hero=x.id===w.id);saveDraft(true);render()});change(vis,e=>w.visible=e.target.checked);
rep.addEventListener('change',async()=>{if(!rep.files?.[0])return;busy(true);try{const blob=await imageToWebp(rep.files[0]);w.originalSrc=w.originalSrc||w.src;w.src=fname(i+1);w.blob=blob;w.previewUrl=URL.createObjectURL(blob);w.isReplaced=true;saveDraft(true);render();status('<p>画像を差し替えました。公開前なら取消できます。</p>','success')}catch(e){status(`<p>${esc(e.message)}</p>`,'error')}finally{busy(false)}});undo.addEventListener('click',()=>{if(w.previewUrl)URL.revokeObjectURL(w.previewUrl);w.src=w.originalSrc||w.src;w.originalSrc='';w.blob=null;w.previewUrl='';w.isReplaced=false;saveDraft(true);render()});
n.querySelector('.move-up').disabled=i===0;n.querySelector('.move-down').disabled=i===works.length-1;n.querySelector('.move-up').onclick=()=>move(i,i-1);n.querySelector('.move-down').onclick=()=>move(i,i+1);n.querySelector('.duplicate-button').onclick=()=>duplicate(i);n.querySelector('.remove-button').onclick=()=>remove(i);card.addEventListener('dragstart',e=>{dragIndex=i;card.classList.add('dragging');e.dataTransfer.effectAllowed='move'});card.addEventListener('dragend',()=>{dragIndex=-1;card.classList.remove('dragging')});card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();if(dragIndex>=0)move(dragIndex,i)});list.appendChild(n)})}
function cardHtml(w){const sc=w.size&&w.size!=='normal'?` ${w.size}`:'',tag=(w.tags||[]).join('|'),meta=`data-work-id="${esc(w.id)}" data-category="${esc(w.category)}" data-description="${esc(w.description)}" data-tags="${esc(tag)}" data-created-at="${esc(w.createdAt||'')}" data-published-at="${esc(w.publishedAt||'')}" data-focal-x="${w.focalX??50}" data-focal-y="${w.focalY??35}"`;return`<article class="work-card${sc}" ${meta}><img src="${esc(w.src)}" loading="lazy" decoding="async" alt="${esc((w.title||'作品')+'のイラスト')}" style="object-position:${w.focalX??50}% ${w.focalY??35}%"><div class="work-info"><span>${esc({girl:'女の子',stream:'配信系',event:'記念・お祝い',other:'その他'}[w.category]||'作品')}</span><h3>${esc(w.title||'無題')}</h3></div></article>`}
function buildHtml(){const d=new DOMParser().parseFromString(sourceHtml,'text/html'),g=d.querySelector('.gallery');if(!g)throw new Error('作品一覧が見つかりません');const visible=works.filter(w=>w.visible!==false),hidden=works.filter(w=>w.visible===false);g.innerHTML='\n'+visible.map(cardHtml).join('\n')+'\n';let t=d.querySelector('#portfolio-hidden-works');if(!t){t=d.createElement('template');t.id='portfolio-hidden-works';d.body.appendChild(t)}t.innerHTML=hidden.map(cardHtml).join('\n');const hero=visible.find(w=>w.hero)||visible[0],subs=visible.filter(w=>!hero||w.id!==hero.id).slice(0,2);if(hero){const hi=d.querySelector('.main-card img');if(hi){hi.src=hero.src;hi.alt=(hero.title||'作品')+'のイラスト';hi.style.objectPosition=`${hero.focalX??50}% ${hero.focalY??35}%`}const og=d.querySelector('meta[property="og:image"]');if(og)og.content=PUBLIC+hero.src}const a=d.querySelector('.card-top img'),b=d.querySelector('.card-bottom img');if(a&&subs[0])a.src=subs[0].src;if(b&&subs[1])b.src=subs[1].src;const count=d.querySelector('.hero-stats strong');if(count)count.textContent=String(visible.length);return '<!DOCTYPE html>\n'+d.documentElement.outerHTML}
async function loadHistory(){const commits=await api('/commits?path=index.html&per_page=20');historySelect.innerHTML='<option value="">履歴を選択</option>'+commits.map(c=>`<option value="${c.sha}">${esc(new Date(c.commit.author.date).toLocaleString('ja-JP'))} — ${esc(c.commit.message)}</option>`).join('')}
async function loadPortfolio(){token=tokenInput.value.trim();if(!token)return status('<p>GitHubトークンを入力してください。</p>','error');remember.checked?sessionStorage.setItem('irochi_github_token',token):sessionStorage.removeItem('irochi_github_token');busy(true);try{const f=await api('/contents/index.html?ref=main');indexSha=f.sha;sourceHtml=dec(f.content);parseHtml(sourceHtml);statusBadge.textContent='接続済み';statusBadge.classList.add('connected');editor.classList.remove('hidden');render();await loadHistory();saveDraft(true)}catch(e){status(`<p>読み込みに失敗しました。</p><p>${esc(e.message)}</p>`,'error')}finally{busy(false)}}
fileInput.addEventListener('change',async()=>{const fs=[...fileInput.files];if(!fs.length)return;busy(true);try{for(let i=0;i<fs.length;i++){const blob=await imageToWebp(fs[i]),u=URL.createObjectURL(blob);works.push({id:crypto.randomUUID(),src:fname(i+1),title:fs[i].name.replace(/\.[^.]+$/,''),category:'girl',size:'normal',description:'',tags:[],createdAt:new Date().toISOString().slice(0,10),publishedAt:new Date().toISOString().slice(0,10),focalX:50,focalY:35,visible:true,hero:works.length===0,isNew:true,isReplaced:false,originalSrc:'',previewUrl:u,blob})}saveDraft(true);render()}catch(e){status(`<p>${esc(e.message)}</p>`,'error')}finally{fileInput.value='';busy(false)}})
async function publish(){if(!token)return status('<p>先に接続してください。</p>','error');busy(true);publishBtn.disabled=true;try{status('<p>1/3 画像をアップロードしています…</p>');for(const w of works.filter(x=>x.blob)){await api('/contents/'+w.src,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`作品画像を追加: ${w.title}`,content:await b64(w.blob),branch:BRANCH})})}status('<p>2/3 最新のHTMLを確認しています…</p>');const latest=await api('/contents/index.html?ref=main');sourceHtml=dec(latest.content);indexSha=latest.sha;const html=buildHtml();status('<p>3/3 作品情報を公開しています…</p>');await api('/contents/index.html',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'作品管理画面からポートフォリオを更新',content:enc(html),sha:indexSha,branch:BRANCH})});sourceHtml=html;works.forEach(w=>{if(w.previewUrl)URL.revokeObjectURL(w.previewUrl);w.blob=null;w.previewUrl='';w.isNew=false;w.isReplaced=false;w.originalSrc=''});saveDraft(true);render();await loadHistory();status(`<p><strong>公開処理が完了しました。</strong></p><p>GitHub Pagesへの反映には通常数十秒〜数分かかります。</p><p><a href="${PUBLIC}" target="_blank">公開サイトを確認する</a></p>`,'success')}catch(e){status(`<p><strong>公開に失敗しました。</strong></p><p>${esc(e.message)}</p>`,'error')}finally{publishBtn.disabled=false;busy(false)}}
$('#load-history').onclick=async()=>{const sha=historySelect.value;if(!sha)return status('<p>履歴を選択してください。</p>','error');if(!confirm('選択した履歴を編集中の状態へ読み込みますか？'))return;busy(true);try{const f=await api(`/contents/index.html?ref=${sha}`);const html=dec(f.content);parseHtml(html);saveDraft(true);render();status('<p>履歴を読み込みました。確認後「変更を公開」で復元できます。</p>','success')}catch(e){status(`<p>${esc(e.message)}</p>`,'error')}finally{busy(false)}};
loadBtn.onclick=loadPortfolio;publishBtn.onclick=publish;$('#save-draft').onclick=()=>saveDraft();$('#load-draft').onclick=loadDraft;$('#clear-draft').onclick=clearDraft;tokenInput.addEventListener('keydown',e=>{if(e.key==='Enter')loadPortfolio()});